'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TakeABreakReminder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm04() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm05() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm06() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm07() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm08() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm09() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarm10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarm10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property chimes() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("chimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property chord() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("chord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ir_begin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ir_begin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ir_end() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ir_end", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ir_inter() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ir_inter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property notify() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property recycle() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("recycle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring04() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring05() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring06() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring07() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring08() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring09() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ring10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ringout() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ringout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speech_Disambiguation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speech_Disambiguation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speech_Misrecognition() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speech_Misrecognition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speech_Off() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speech_Off", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speech_On() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speech_On", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speech_Sleep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speech_Sleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property tada() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Background() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Background", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Balloon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Balloon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Battery_Critical() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Battery_Critical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Battery_Low() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Battery_Low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Critical_Stop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Critical_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Default() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Ding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Exclamation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Exclamation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Feed_Discovered() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Feed_Discovered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Foreground() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Foreground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Hardware_Fail() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Hardware_Fail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Hardware_Insert() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Hardware_Insert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Hardware_Remove() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Hardware_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Information_Bar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Information_Bar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Logoff_Sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Logoff_Sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Logon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Logon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Menu_Command() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Menu_Command", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Message_Nudge() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Message_Nudge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Minimize() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Minimize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Navigation_Start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Navigation_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Notify() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Notify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Notify_Calendar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Notify_Calendar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Notify_Email() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Notify_Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Notify_Messaging() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Notify_Messaging", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Notify_System_Generic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Notify_System_Generic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Pop_up_Blocked() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Pop_up_Blocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Print_complete() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Print_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Proximity_Connection() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Proximity_Connection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Proximity_Notification() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Proximity_Notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Recycle() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Recycle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Restore() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Ringin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Ringin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Ringout() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Ringout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Shutdown() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Startup() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Startup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Unlock() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Unlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_User_Account_Control() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_User_Account_Control", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
